name: Test

on: [push, pull_request]

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
